### ISSUE TITLE
When an invalid domain is passed, it throws an error (null string)

### ISSUE THREAD

**Issue by arpitj007** [iSurcouf/Simple-DNS-Lookup#1]
When you pass an invalid domain address, it throws an error instead of Undefined. All DNS records must be updated
This should be the fix
`
			<?php $result_aaaa = empty($dns_aaaa); if($result_aaaa != null){ ?>
			<tr class = "warning">
				<td class="vert-align text-center"><h4>AAAA</h4></td>
				<td class="vert-align text-center">/</td>
				<td class="vert-align text-center">/</td>
				<td><h4>No AAAA record for this server (IPV6)</h4></td>
			</tr>
			<?php } 
`

**Comment by iSurcouf** [comment]
Thanks, that's fixed !
