### ISSUE TITLE
css not displaying

### ISSUE THREAD

**Issue by kenpachizero** [iSurcouf/Simple-DNS-Lookup#3]
Hello, i have tried your php and css file but its not displaying correctly if you go to https://dns.jsh.digital/
i see you have:  
```
<!-- Bootstrap core CSS -->
<link href="css/bootstrap.min.css" rel="stylesheet">
```
in yours as well, is that required for it to display correctly?

**Comment by iSurcouf** [comment]
Correct. That's fixed.
